pipeline {
    agent {
        docker {
            image 'maven:3-alpine'
            args '-v /root/.m2:/root/.m2'
        }
    }
    stages {
        stage('Build') {
            steps {
                sh 'mvn -B -DskipTests clean package'
            }
        }
        stage('Test') {
            steps {
                sh 'mvn test'
            }
            post {
                always {
                    junit 'target/surefire-reports/*.xml'
                }
            }
        }
        stage('Deliver') {
            steps {
                sh './jenkins/scripts/deliver.sh'
            }
        }
        stage('Email Notification'){
            mail bcc: '', body: '''Build successful!!!
            Thanks,
            Salim''', cc: '', from: '', replyTo: '', subject: 'Build successfull', to: 'salim.khan.wk@gmail.com'
            }
    }
}
